name: pipeline_dbt
version: "1.0.0"

profile: "pipeline_dbt" # Assure-toi que ce profil existe dans ton profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  pipeline_dbt:
    martz: # si tu utilises ce dossier dans models/
      +materialized: view # Par défaut, tous les modèles sous martz seront des vues
